dev/ruby/learn/ror/blog/config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'

end

dev/ruby/learn/ror/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

dev/ruby/learn/ror/blog/app/models/contact.rb
class Contact < ApplicationRecord
end

dev/ruby/learn/ror/blog/app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true, length: {minimum: 5}
  
end

dev/ruby/learn/ror/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

dev/ruby/learn/ror/blog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :lastname, :email, :phone, :org)
    end
end

dev/ruby/learn/ror/blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @name = "Forcepoint"
  end

  def contacts
  end

end

dev/ruby/learn/ror/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  private def post_params
    params.require(:post).permit(:title, :body)
  end

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if (@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    # # @product = Product.new({:serial => params[:serial], :value => params[:value]})

    @post = Post.new(post_params)
    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

end

dev/ruby/learn/ror/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

dev/ruby/learn/ror/blog/app/helpers/contacts_helper.rb
module ContactsHelper
end

dev/ruby/learn/ror/blog/app/helpers/pages_helper.rb
module PagesHelper
end

dev/ruby/learn/ror/blog/app/helpers/posts_helper.rb
module PostsHelper
end

dev/ruby/learn/ror/blog/app/views/contacts/_contact.html.erb
<div class="container-fluid py-5 bg-secondary m-5 mr-6">
  <h3 class="display-7 fw-bold">
    <%= contact.name + " " + contact.lastname %>
  </h3>
        
        <div id="<%= dom_id contact %>" class="card col-md-6 fs-5 m-3">

  <table class="table m-3">

    <tr>
      <td>Name:</td>
      <td><%= contact.name %></td>
    </tr>

    <tr>
      <td>Lastname:</td>
      <td><%= contact.lastname %></td>
    </tr>

    <tr>
      <td>Email:</td>
      <td><%= contact.email %></td>
    </tr>

    <tr>
      <td>Phone:</td>
      <td><%= contact.phone %></td>
    </tr>

    <tr>
      <td>Org:</td>
      <td><%= contact.org %></td>
    </tr>

  </table>

</div>


        <button class="btn btn-primary btn-lg" type="button">Example button</button>
</div>

dev/ruby/learn/ror/blog/app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="col-1">
  </div>

  <div class="col-6">

  <div class="m-3">
    <label>Name</label>
    <%= form.text_field(:name, {:class => 'form-control'}) %>
  </div>

  <div class="m-3">
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field(:lastname, {:class => 'form-control'}) %>
  </div>

  <div class="m-3">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field(:email, {:class => 'form-control'}) %>
  </div>

  <div class="m-3">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field(:phone, {:class => 'form-control'}) %>
  </div>

  <div class="m-3">
    <%= form.label :org, style: "display: block" %>
    <%= form.text_field(:org, {:class => 'form-control'}) %>
  </div>

  <div class="m-3">
    <input type="submit" name="commit" value="Save" class="btn btn-success"/>
  </div>

  </div>

  </div>

<% end %>

dev/ruby/learn/ror/blog/app/views/contacts/_partialdemo.html.erb
<h3>Hey! This is from partial!</h3>

dev/ruby/learn/ror/blog/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

dev/ruby/learn/ror/blog/app/views/contacts/index.html.erb
<div class="content m-4">

  <div class="mb-3">

    <p style="color: green"><%= notice %></p>
    <strong>Contacts</strong> <%= link_to "Add", new_contact_path %>

  </div>


<div id="contacts">
  <table class="table table-bordered table-striped">

    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Org</th>
        <th>Action</th>
      </tr>
    </thead>



  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.lastname %></td>
      <td><%= contact.email %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.org %></td>
      <td><%= link_to "Show", contact %></td>
    </tr>
  <% end %>

  </table>
</div>

</div>

dev/ruby/learn/ror/blog/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

dev/ruby/learn/ror/blog/app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact), class: 'btn btn-primary' %>
  <%= link_to "Back to contacts", contacts_path, class: 'btn btn-primary' %>
  <%= button_to "Delete", @contact, method: :delete, class: 'btn btn-danger' %>
</div>

dev/ruby/learn/ror/blog/app/views/layouts/_nav.html.erb
<nav class="mb-4 d-flex justify-content-between">

    <ul class="d-flex align-items-center">

        <li><%= link_to "Home", "/", class:"p-3" %></li>
        <li><%= link_to "Posts", posts_path, class:"p-3" %></li>
        <li><%= link_to "Contacts", contacts_path, class:"p-3" %></li>

    </ul>

    <ul class="d-flex align-items-center">

        <li>
            <a href="/profile" id="a-profile" class="p-3">Username</a>
        </li>

        <li>
            <a href="/logout" class="p-3">Logout</a>
        </li>

    </ul>

</nav>

dev/ruby/learn/ror/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>

  nav>ul>li>a {
      text-decoration: none;
      color: white;
  }

  nav>ul>li>a:hover {
      text-decoration: none;
      color: orange;
  }

  nav>ul>li>a.active {
      text-decoration: none;
      color: red;
  }

  .nav-link.active {
      text-decoration: none;
      color: red;
  }

  nav>ul>li {
      list-style: none;
  }

  nav {
      background-color: black;
      padding-top: 10px;
  }

  body {
      /* background-color: #6c757d; */
      background-color: #f1f1f1;
      overflow-x: hidden;
      overflow-y: auto;
  }

  </style>


  </head>

  <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

  </body>
</html>

dev/ruby/learn/ror/blog/app/views/pages/about.html.erb
<h3>About</h3>

<%= @name %>

dev/ruby/learn/ror/blog/app/views/pages/contacts.html.erb
<h3>Contacts!</h3>

dev/ruby/learn/ror/blog/app/views/posts/edit.html.erb
<h3>Edit This!</h3>



<div class="row">

  <div class="col-1"></div>

  <div class="col-3">

<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>

errors below:

<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>

<% end %>

<div class="m-3">
  <label>Title</label>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</div>

<div class="m-3">
  <label>Content</label>
  <%= f.text_area(:body, {:class => 'form-control', :rows => 5}) %>
</div>

<div class="m-3">
  <input type="submit" name="commit" value="Save" class="btn btn-success"/>
</div>

<% end %>

  </div>

  <div class="col-1"></div>

</div>

dev/ruby/learn/ror/blog/app/views/posts/index.html.erb
<h3>List of Posts</h3>

<% @post.each do |post| %>

<div class="row">

    <div class="col-1">
    </div>

    <div class="card col-3 m-3 pb-3">
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to "Read...", post_path(post), :class => "btn btn-outline-primary" %>

    </div>

</div>


<% end %>

dev/ruby/learn/ror/blog/app/views/posts/new.html.erb
<div class="row">

  <div class="col-1"></div>

  <div class="col-3">

<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>

errors below:

<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>

<% end %>

<div class="m-3">
  <label>Title</label>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</div>

<div class="m-3">
  <label>Content</label>
  <%= f.text_area(:body, {:class => 'form-control', :rows => 5}) %>
</div>

<div class="m-3">
  <input type="submit" name="commit" value="Save" class="btn btn-success"/>
</div>

<% end %>

  </div>

  <div class="col-1"></div>

</div>

dev/ruby/learn/ror/blog/app/views/posts/show.html.erb
<h3><%= @post.title %></h3>

<p><%= @post.body %></p>

<hr>

<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning'  %>

<%= link_to "Delete", post_path(@post), :method => 'delete', data: {confirm: "Delete?"}, :class => 'btn btn-danger'  %>